// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Helper to get required environment variable or throw error
  static String _getEnv(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw Exception(
        'Missing required environment variable: $key\n'
        'Please create a .env file with all required Firebase configuration values.\n'
        'See .env.example for reference.',
      );
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_WEB_API_KEY'),
    appId: _getEnv('FIREBASE_WEB_APP_ID'),
    messagingSenderId: _getEnv('FIREBASE_WEB_MESSAGING_SENDER_ID'),
    projectId: _getEnv('FIREBASE_WEB_PROJECT_ID'),
    authDomain: _getEnv('FIREBASE_WEB_AUTH_DOMAIN'),
    storageBucket: _getEnv('FIREBASE_WEB_STORAGE_BUCKET'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_ANDROID_API_KEY'),
    appId: _getEnv('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _getEnv('FIREBASE_ANDROID_MESSAGING_SENDER_ID'),
    projectId: _getEnv('FIREBASE_ANDROID_PROJECT_ID'),
    storageBucket: _getEnv('FIREBASE_ANDROID_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_IOS_API_KEY'),
    appId: _getEnv('FIREBASE_IOS_APP_ID'),
    messagingSenderId: _getEnv('FIREBASE_IOS_MESSAGING_SENDER_ID'),
    projectId: _getEnv('FIREBASE_IOS_PROJECT_ID'),
    storageBucket: _getEnv('FIREBASE_IOS_STORAGE_BUCKET'),
    iosBundleId: _getEnv('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_MACOS_API_KEY'),
    appId: _getEnv('FIREBASE_MACOS_APP_ID'),
    messagingSenderId: _getEnv('FIREBASE_MACOS_MESSAGING_SENDER_ID'),
    projectId: _getEnv('FIREBASE_MACOS_PROJECT_ID'),
    storageBucket: _getEnv('FIREBASE_MACOS_STORAGE_BUCKET'),
    iosBundleId: _getEnv('FIREBASE_MACOS_BUNDLE_ID'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _getEnv('FIREBASE_WINDOWS_API_KEY'),
    appId: _getEnv('FIREBASE_WINDOWS_APP_ID'),
    messagingSenderId: _getEnv('FIREBASE_WINDOWS_MESSAGING_SENDER_ID'),
    projectId: _getEnv('FIREBASE_WINDOWS_PROJECT_ID'),
    authDomain: _getEnv('FIREBASE_WINDOWS_AUTH_DOMAIN'),
    storageBucket: _getEnv('FIREBASE_WINDOWS_STORAGE_BUCKET'),
  );
}
